version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t coworking-analytics .
      - echo "Tagging the Docker image..."
      - docker tag coworking-analytics:latest $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/coworking-analytics:$CODEBUILD_BUILD_NUMBER
  post_build:
    commands:
      - echo "Pushing the Docker image to Amazon ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/coworking-analytics:$CODEBUILD_BUILD_NUMBER

artifacts:
  files:
    - '**/*'

